print("hello!")
print("STANDING BY YA WAITING AT YOUR BACK DOOR ALLLL THIS TIME HOW COULD YOU NOT KNOW THAT BABYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEY YOU BELONG WITH MEEEEEEEEEESEEEEEEEEEEEEE you belong with me")
print("*epic acoustic guitar solo*")
